---
id: "product.summary"
name: "Product Summary"
functions:
- name: "Product Summary"
  functionId: "1006"
  functionCode: "product.summary"
  resourceName: "Product Summary"
  resourceCode: "product.summary"
  privileges:
  - privilege: "view"
    supportsLimit: false
  - privilege: "edit"
    supportsLimit: false
