{{- $fullName := include "app.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    {{- range required "ingressHostnames array required" .Values.ingressHostnames }}
    - host: {{ . }}
      http:
        paths:
          - path: /{{ $.Chart.Name }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: 8080
    {{- end }}