backbase:
  stream:
    generator:
      product:
        kinds:
          kind1:
            distribution:
              1: 1.0
              2: 0.5
            amountScale: 2
            minimumAvailableBalance: 200.0
            maximumAvailableBalance: 5000.0
            currency: "EUR"
            generateIban: true
            generateBBAN: false
            debitCardDistribution:
              1: 1.0
            ibanCountryCode: "NL"
            bbanPattern: "^[A-Z]{4}\\d{10}"
            cardIdPattern: "^[A-Z]{3}\\d{2}"
            cardTypes:
              - "VISA"
              - "MASTERCARD"
              - "MAESTRO"
            errorRateUnknownProductId: 0.0
            errorRateEmptyLegalEntity: 0.0
            errorRateEmptyAccountBalance: 0.0
            idPattern: "[A-Z]{5}[1-9]{2}"
            accountBalanceAsBookedBalance: true
          kind2:
            distribution:
              1: 0.5
            amountScale: 2
            minimumBookedBalance: 200.0
            maximumBookedBalance: 20000.0
            currency: "EUR"
            generateIban: true
            generateBBAN: false
            debitCardDistribution:
              1: 1.0
            ibanCountryCode: "NL"
            bbanPattern: "^[A-Z]{4}\\d{10}"
            cardIdPattern: "^[A-Z]{3}\\d{2}"
            cardTypes:
              - "VISA"
              - "MASTERCARD"
              - "MAESTRO"
            errorRateUnknownProductId: 0.0
            errorRateEmptyLegalEntity: 0.0
            errorRateEmptyAccountBalance: 0.0
            idPattern: "[A-Z]{5}[1-9]{2}"
            accountBalanceAsBookedBalance: true
          kind3:
            distribution:
              1: 0.5
            amountScale: 2
            minimumAvailableBalance: 200.0
            maximumAvailableBalance: 5000.0
            currency: "EUR"
            generateIban: false
            generateBBAN: false
            debitCardDistribution:
              1: 1.0
            ibanCountryCode: "NL"
            bbanPattern: "^[A-Z]{4}\\d{10}"
            cardIdPattern: "^[A-Z]{3}\\d{2}"
            cardTypes:
              - "VISA"
              - "MASTERCARD"
              - "MAESTRO"
            errorRateUnknownProductId: 0.0
            errorRateEmptyLegalEntity: 0.0
            errorRateEmptyAccountBalance: 0.0
            idPattern: "[A-Z]{5}[1-9]{2}"
            accountBalanceAsBookedBalance: true
          kind4:
            distribution:
              1: 1.0
              2: 0.5
            amountScale: 2
            minimumAvailableBalance: 0.0
            maximumAvailableBalance: 2000.0
            currency: "EUR"
            generateIban: true
            generateBBAN: true
            debitCardDistribution:
              1: 1.0
            ibanCountryCode: "NL"
            bbanPattern: "^[A-Z]{4}\\d{10}"
            cardIdPattern: "^[A-Z]{3}\\d{2}"
            cardTypes:
              - "VISA"
              - "MASTERCARD"
              - "MAESTRO"
            errorRateUnknownProductId: 0.0
            errorRateEmptyLegalEntity: 0.0
            errorRateEmptyAccountBalance: 0.0
            idPattern: "[A-Z]{5}[1-9]{2}"
            accountBalanceAsBookedBalance: true
