# Stream config
spring:
  cloud:
    kubernetes:
      discovery:
        # Set to false if using Eureka for service discovery
        enabled: true
  zipkin:
    enabled: false
  security:
    oauth2:
      client:
        registration:
          dbs:
            authorization-grant-type: client_credentials
            client-id: bb-client
            client-secret: bb-secret
            client-authentication-method: post
        provider:
          dbs:
            token-uri: http://token-converter:8080/oauth/token
backbase:
  stream:
    dbs:
      access-group-presentation-base-url: http://access-control:8080
logging:
  level:
    root: INFO

