generator:
  transaction:
    type-groups:
      - Payment
      - Withdrawal
      - Loans
      - Fees
    transaction-types:
      - ATM
      - ACH
      - Bill Payment
      - Cash
      - Cheques
      - Credit/Debit Card
      - Check
      - Deposit
      - Fee
      - POS
      - Withdrawal
    debit-retail-categories:
      - Food Drinks
      - Transportation
      - Home
      - Health Beauty
      - Shopping
      - Bills Utilities
      - Hobbies Entertainment
      - Transfers
      - Uncategorised
      - Car
      - Beauty
      - Health Fitness
      - Mortgage
      - Rent
      - Public Transport
      - Internet
      - Mobile Phone
      - Utilities
      - Alcohol Bars
      - Fast Food
      - Groceries
      - Restaurants
      - Clothing
      - Electronics
    credit-retail-categories:
      - Income
      - Other Income
      - Bonus
      - Salary/Wages
      - Interest Income
      - Rental Income-