management.metrics.export.prometheus.enabled: false
spring.cloud.kubernetes.config.enabled: false


spring:
  security:
    oauth2:
      client:
        provider:
          dbs:
            token-uri: https://stream-demo.proto.backbasecloud.com/api/token-converter/oauth/token
        registration:
          dbs:
            authorization-grant-type: client_credentials
            client-id: bb-client
            client-secret: bb-secret
            client-authentication-method: post

backbase:
  stream:
    dbs:
      access-group-presentation-base-url: https://stream-api.proto.backbasecloud.com/accessgroup-presentation-service/service-api/v2
      account-presentation-base-url: https://stream-api.proto.backbasecloud.com/account-presentation-service/service-api/v2
      legal-entity-presentation-base-url:  https://stream-api.proto.backbasecloud.com/legalentity-presentation-service/service-api/v2
      user-presentation-base-url: https://stream-api.proto.backbasecloud.com/user-presentation-service/service-api/v2
      transaction-presentation-base-url: https://stream-api.proto.backbasecloud.com/transaction-presentation-service/service-api/v2

logging:
  level:
    root: debug


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"

bootstrap:
  product-catalog:
    productKinds:
      - externalKindId: "insurance"
        kindName: "Insurance"
        kindUri: "insurance"
    productTypes:
      - externalProductId: "standard-account"
        externalProductKindId: "kind1"
        productTypeName: "Standard Account"
      - externalProductId: "deluxe-account"
        externalProductKindId: "kind1"
        productTypeName: "Deluxe Account"
      - externalProductId: "flexible-savings-account"
        externalProductKindId: "kind2"
        productTypeName: "Flexible Savings"
      - externalProductId: "children-savings-account"
        externalProductKindId: "kind2"
        productTypeName: "Children Savings"
      - externalProductId: "credit-card"
        externalProductKindId: "kind3"
        productTypeName: "Credit Card"
      - externalProductId: "gold-card"
        externalProductKindId: "kind3"
        productTypeName: "Gold Card"
      - externalProductId: "platinum-cart"
        externalProductKindId: "kind3"
        productTypeName: "Platinum Card"
      - externalProductId: "debit-card"
        externalProductKindId: "kind4"
        productTypeName: "Debit Card"
      - externalProductId: "personal-loan"
        externalProductKindId: "kind7"
        productTypeName: "Personal Loan"
      - externalProductId: "flexible-loan"
        externalProductKindId: "kind7"
        productTypeName: "Flexible Loan"
      - externalProductId: "guided-investment-account"
        externalProductKindId: "kind5"
        productTypeName: "Guided Investment Account"
      - externalProductId: "self-directed-investment-account"
        externalProductKindId: "kind5"
        productTypeName: "Self Directed Investment Account"
      - externalProductId: "term-deposit-5"
        externalProductKindId: "kind6"
        productTypeName: "Term Deposit 5 years"
      - externalProductId: "term-deposit-10"
        externalProductKindId: "kind6"
        productTypeName: "Term Deposit 10 years"
      - externalProductId: "travel-insurance"
        externalProductKindId: "insurance"
        productTypeName: "Travel Insurance"
      - externalProductId: "home-insurance"
        externalProductKindId: "insurance"
        productTypeName: "Home Insurance"