spring:
  zipkin:
    enabled: false
  security:
    oauth2:
      client:
        registration:
          dbs:
            authorization-grant-type: client_credentials
            client-id: bb-client
            client-secret: bb-secret
            client-authentication-method: post
        provider:
          dbs:
            token-uri: http://token-converter:8080/oauth/token

backbase:
  stream:
    legalentity:
    sink:
      useIdentityIntegration: true
    dbs:
      user-manager-base-url: http://user-manager:8080
      access-control-base-url: http://access-control:8080
      arrangementManagerBaseUrl: http://arrangement-manager:8080

---
spring:
  config:
    activate:
      on-profile: moustache-bank

bootstrap:
  # This is just na example. Replace it with data corresponding to your bank
  legalEntity:
    name: "Moustache Bank"
    realmName: "backbase"
    externalId: "moustache-bank"
    legalEntityType: "BANK"
    referenceJobRoles:
      - name: Entitlements - Manager
        description: Full Entitlements administration.
        functionGroups:
          - name: "Manage Entitlements"
            functions:
              - functionId: "1019"
                functionCode: "manage.data.groups"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
                  - privilege: "delete"
                  - privilege: "approve"
              - functionId: "1020"
                functionCode: "manage.function.groups"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
                  - privilege: "delete"
                  - privilege: "approve"
      - name: Retail User - USA
        description: Retail User Permissions for USA
        functionGroups:
          - name: "Products, payments, txn, contacts"
            functions:
              - functionId: "1006"
                functionCode: "product.summary"
                privileges:
                  - privilege: "view"
              - functionId: "1003"
                functionCode: "transactions"
                privileges:
                  - privilege: "view"
                  - privilege: "edit"
              - functionId: "1017"
                functionCode: "us.domestic.wire"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
              - functionId: "1018"
                functionCode: "us.foreign.wire"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
              - functionId: "1005"
                functionCode: "contacts"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
                  - privilege: "delete"
    administrators:
      - externalId: "admin"
        fullName: "Backbase Root Admin"
        identityLinkStrategy: "CREATE_IN_IDENTITY"
        emailAddress:
          address: "bbadmin@email.com"
        mobileNumber:
          number: "1234567890"
    users:
      - user:
          externalId: "admin"
          identityLinkStrategy: "CREATE_IN_IDENTITY"
        referenceJobRoleNames:
          - "Entitlements - Manager"
