openapi: 3.0.3

info:
  title: Stream Composition Service API Spec
  description: Specs for Stream Composition Service API
  version: 1.1.0

servers:
  - description: local test
    url: http://localhost:8080/api/v1

tags:
  - name: Retail

paths:

  /service-api/v1/stream-composition:
    description: No description available