openapi: 3.0.3
info:
  title: Legal entity composition API
  version: 1.0.0
servers:
  - url: http://localhost:8080/service-api/v1
    description: The server
tags:
  - name: LegalEntityComposition
paths:
  /service-api/v2/composition:
    post:
      tags:
        - LegalEntityComposition
      summary: Initializes/Creates legal entity composition
      description: Initializes/Creates legal entity composition
      operationId: initializeComposition
      requestBody:
        description: Initialize Composition Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitializeCompositionRequest'

      responses:
        "201":
          description: Legal Entity composition initialized.
          content:
            application/json:
              schema:
                type: string
                nullable: true
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    BadRequest:
      required:
        - message
      type: object
      properties:
        message:
          type: string
    InitializeCompositionRequest:
      type: object
      properties:
        id:
          type: string
        value:
          type: string
    InternalServerError:
      required:
        - message
      type: object
      properties:
        message:
          type: string

