apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.dockerRegistry }}/dbp/{{ .Chart.Name }}:{{ .Values.version }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: spring-environment
          env:
            - name: CHART_NAME
              value: "{{ .Chart.Name }}"
            - name: ACTIVEMQ_OPTS
              value: "-Xmx4g -Dorg.apache.activemq.UseDedicatedTaskRunner=false -Dserver.name=$HOSTNAME -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=8686 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=8686 -Djava.rmi.server.hostname=localhost -javaagent:/opt/elastic-apm-agent-1.20.0.jar"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              memory: "4Gi"