apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: activemq
      port: 61616
      targetPort: 61616
      protocol: TCP
    - name: activemqadmin
      port: 8161
      targetPort: 8161
      protocol: TCP
  selector:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
