openapi: 3.0.3
info:
  title: Config
  description: No description available
  version: 1.0.0
servers:
  - url: /wsecu-config-service/
    description: The server
tags:
  - name: MainOperations
paths:
  /service-api/v2/composition:
    post:
      tags:
        - MainOperations
      summary: Initializes/Creates Legal Entity Composition
      description: Initializes/Creates Legal Entity Composition
      operationId: initializeComposition
      requestBody:
        description: Initialize Composition Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitializeCompositionRequest'

      responses:
        "201":
          description: Legal Entity composition initialized.
          content:
            application/json:
              schema:
                type: string
                nullable: true
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    BadRequest:
      required:
        - message
      type: object
      properties:
        message:
          type: string
    InitializeCompositionRequest:
      type: object
      properties:
        id:
          type: string
        value:
          type: string
    GetConfigResponse:
      type: array
      items:
        $ref: '#/components/schemas/ConfigItem'
    InternalServerError:
      required:
        - message
      type: object
      properties:
        message:
          type: string

